name: daily-devcard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Download DevCard
        run: |
          curl -o devcard.png "https://devcard-url?username=${{ secrets.USER_ID }}&layout=wide"
      
      - name: Commit and push DevCard
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add devcard.png
          git commit -m "chore: update devcard"
          git push
